# Based on https://dev.to/daslaw/deploying-a-vite-app-to-github-pages-using-github-actions-a-step-by-step-guide-2p4h
name: packages/demos/email-recovery

on:
  push:
    branches: ['main', 'feature/email-recovery-ui-integration']
    paths:
        - packages/demos/email-recovery/**
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
    run:
        working-directory: ./packages/demos/email-recovery

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: packages/demos/email-recovery/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Copy .env.base-sepolia
        run: cp .env.base-sepolia .env
      - name: Build
        env:
          VITE_WALLET_CONNECT_PROJECT_ID: ${{ secrets.VITE_WALLET_CONNECT_PROJECT_ID }}
        run: VITE_WALLET_CONNECT_PROJECT_ID=${VITE_WALLET_CONNECT_PROJECT_ID} yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './packages/demos/email-recovery/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1