name: packages/plugins

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - packages/plugins/**

defaults:
  run:
    working-directory: ./packages/plugins

jobs:
  foundry:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # Uncomment the lines below to install & generate zk assets
      # - working-directory: ./packages/zkp/lib/circom
      #   run: cargo build --release

      # - working-directory: ./packages/zkp/lib/circom
      #   run: cargo install --path circom

      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: "18.x"
      #     cache: "yarn"
      #     cache-dependency-path: packages/zkp/yarn.lock

      # - working-directory: ./packages/zkp
      #   run: yarn install --frozen-lockfile

      # - working-directory: ./packages/zkp
      #   run: yarn build

      # - working-directory: ./packages/plugins
      #   run: yarn install --frozen-lockfile

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      # Skip safe zk email recovery unit tests while finishing demo. We still have a passing integration test - SafeZkEmailRecoveryPluginIntegration.t.sol
      - name: Run Forge tests
        run: |
          forge test --no-match-path test/unit/safe/SafeZkEmailRecoveryPlugin.t.sol -vvv
        id: test

  hardhat:
    strategy:
      fail-fast: true

    name: Hardhat project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"
          cache-dependency-path: packages/plugins/yarn.lock

      # Uncommment the lines below to install & generate zk assets
      # - working-directory: ./packages/zkp/lib/circom
      #   run: cargo build --release

      # - working-directory: ./packages/zkp/lib/circom
      #   run: cargo install --path circom

      # - working-directory: ./packages/zkp
      #   run: yarn install --frozen-lockfile

      # - working-directory: ./packages/zkp
      #   run: yarn build

      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Copy env file
        run: cp .env.example .env

      - name: Run hardhat compile
        run: yarn hardhat compile
